version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: iodb
      POSTGRES_USER: iouser
      POSTGRES_PASSWORD: iosupersecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./api
    environment:
      DATABASE_URL: postgres://iouser:iosupersecretpassword@db/iodb
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - api

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  postgres_data:
